# GitHub Sponsors configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [mohamdben-yahia]
ko_fi: mohamdben_yahia
buy_me_a_coffee: mohamdbenyahia
